config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  resources :users, only: [:new, :create] do
    member do
      get 'downgrade'
    end
  end
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborator
  has_many :users, through: :collaborator
  scope :visible_to, -> (user) { user && (user.premium? || user.admin?) ? all : where(public: true)  }
  scope :publicly_visible, -> {where(public: true)}
  end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
before_action :authenticate_user!

  def index

    @wikis  = policy_scope(Wiki)
    #authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @collaborators = @wiki.collaborators
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user

    @wiki = Wiki.new(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was created."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error creating the wiki. Please try again."
      render :new
    end
  end


  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @collaborators = @wiki.collaborators
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
    if params[:wiki][:collaboration]
      collaborator = User.find_by(email: params[:wiki][:collaboration])
      @wiki.add_collaborator(collaborator.id)
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

        <% if current_user.admin? || current_user.premium? %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
          </div>
        <% end %>

      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Wiki:</p>
     <ul>
       <li>Make is short.</li>
       <li>Keep it interesting.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render "form" %>
   </div>
   <div>
     <%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki } %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1> Wikis </h1>

<div class="row">
    <div class="col-md-8">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to wiki.title, wiki %>
            </h4>
            <small>
              <%= wiki.body %>
            </small>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>

</div>

app/views/wikis/new.html.erb
<% if false %>
<h1> New Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Guidelines for Wikis : </p>
      <ul>
        <li> Ensure your wiki is not a duplicate. </li>
        <li> Proofread! </li>
        <li> Fact check before posting. </li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>

      <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

      <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
</div>
<% end %>

<%= render partial: 'wikis/form' %>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
   <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>